[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]

[build.nixpacksPlan.phases.setup]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0"]

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[[services]]
rootDirectory = "backend"